# Generated by Django 4.1.7 on 2023-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "published"),
                    ("DRAFT", "draft"),
                    ("ACTIVE", "active"),
                ],
                default="PUBLISHED",
                max_length=50,
            ),
        ),
    ]
